variables:
  MAVEN_VERSION: "4.0.0"
  MAVEN_HOME: C:\apache-maven-4.0.0-alpha-7
  JAVA_HOME: C:\Program Files (x86)\Java\jdk1.8.0_181

stages:
  - clean
  - install
  - run

clean:
  tags:
    - Shell-Maven
  stage: clean
  script:
    - mvn clean

install:
  tags:
    - Shell-Maven
  stage: install
  script:
    - mvn clean install
  artifacts:
    name: jarpath
    paths:  
      - target\Integration_Project_Backend-1.0-SNAPSHOT.jar

run:
  tags:
    - Shell-Maven
  stage: run
  script: 
    - java -jar target\Integration_Project_Backend-1.0-SNAPSHOT.jar
  only: 
    - master